services:
  db:
    image: mysql:8.0
    container_name: mysql_rutas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: rutas_universitarias
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_rutas
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: mysql
      DB_NAME: rutas_universitarias
      DB_USER: root
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 3306
